### ISSUE TITLE
Support for Proxies

### ISSUE THREAD

**Issue by eXspir3** [renatoathaydes/rawhttp#13]
It would be really nice if Proxies http,https,socks with authentication would be supported.

**Comment by darkr4y** [comment]
> It would be really nice if Proxies http,https,socks with authentication would be supported.

+1

**Comment by renatoathaydes** [comment]
It is already possible to provide a socket factory for the http client which should allow you to proxy anyway you like, as I mentioned in [this comment](https://github.com/renatoathaydes/rawhttp/issues/2#issuecomment-382003338).

Could you check that out and tell me if that's still not enough for what you're thinking @eXspir3 @darkr4y ?

**Comment by renatoathaydes** [comment]
Example of configuring a socket factory for a client in the tests: https://github.com/renatoathaydes/rawhttp/blob/master/samples/src/test/java/rawhttp/samples/DocsSamples.java#L180

**Comment by eXspir3** [comment]
Thats actually neat! Works great, thank you
