### ISSUE TITLE
The Host header must include port information when not using the default value for the protocol scheme

### ISSUE THREAD

**Issue by parry84** [renatoathaydes/rawhttp#18]
When RawHttp user information from request line to cleanup the value of Host header it strips away the port.

But according to https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23, the Host header must contain the port when it is different that the default 80:

> Host = "Host" ":" host [ ":" port ] ;

**Comment by renatoathaydes** [comment]
Good catch!

But there's a problem with this assertion:

>  the Host header must contain the port when it is different that the default 80

That's not what the RFC says:

> A "host" without any trailing port information implies the default port for the service requested (e.g., "80" for an HTTP URL).

That means that if the URI uses the `http` scheme, it should use the default port for `http` which happens to be 80... but in case of a `https` URI, the [default is 443 instead](https://tools.ietf.org/html/rfc2818#section-2.3).

**Comment by parry84** [comment]
That's correct, I created a new PR (from dev) that also handles HTTPS default port

**Comment by rucek** [comment]
Hi @renatoathaydes, I'm also affected by this bug, any chance to release this shortly?

**Comment by renatoathaydes** [comment]
Sure... but as I had been working a lot on [some new features](https://github.com/renatoathaydes/rawhttp/pull/26), I need to finalize some things first...

**Comment by renatoathaydes** [comment]
Released rawhttp-core version 2.3.0 which fixes this issue. Thanks @parry84 for the help.
