### ISSUE TITLE
[Feature request] support HTTPS (SSL/TLS)

### ISSUE THREAD

**Issue by iddoeldor** [renatoathaydes/rawhttp#2]

**Comment by renatoathaydes** [comment]
How exactly do you want HTTPS support?

Any `HttpMessage` can be written out to a stream using the `com.athaydes.rawhttp.core.HttpMessage#writeTo(java.io.OutputStream)` method (which doesn't care if you're using a `Socket` or a `SSLSocket`.

In the `com.athaydes.rawhttp.core.client.TcpRawHttpClient` class, you can already provide a socket factory via the constructor options which may return a `SSLSocket`.... in `com.athaydes.rawhttp.core.server.TcpRawHttpServer` you can do the same.

**Comment by renatoathaydes** [comment]
I hadn't notice that the default socket creator for `TcpRawHttpClient` did not use a `SSLSocket`. I've fixed that and will release soon.
