### ISSUE TITLE
Question: support for variables?

### ISSUE THREAD

**Issue by jmini** [renatoathaydes/rawhttp#25]
I am not sure if this is out of topic for the `RawHTTP` library, but there are several IDE supporting an Extended version of the HTTP RFC where you can defined environments and custom/system variables.

* VSCode: [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
* IntelliJ Ultimate: [HTTP client](https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html)

---

You can do stuff like this (this is a VSCode example):

```
### Rest client init:
@base_url = http://localhost:8090

### Send ping request:
GET {{base_url}}/ping
Accept: application/json
```

Where `base_url` can be defined in an other file so that you can run the request against different servers (in my eyes related to the question raised in #24).

---

The grammar implemented by IntelliJ is open-source and defined here: [http-request-in-editor-spec](https://github.com/JetBrains/http-request-in-editor-spec). After having a quick look, it seems to me that you can do more with the VSCode extension.

---

I am looking for a way to test the `*.http` files we are writing and I am wondering if `RawHTTP` could be a fit or not.

At the end this can probably be implemented as a pre-processor (you take the `*.http` files that you edit in VSCode, replace the variables based on some context and use `RawHTTP` to send the real HTTP Request).

I am curious about your opinion on this topic. Thank you a lot in advance…

**Comment by renatoathaydes** [comment]
You're in luck :D  I am currently implementing support for the IntelliJ format! It's already almost done... will post back here when I have it working.

**Comment by renatoathaydes** [comment]
I've implemented it in the dev branch... but it's missing a couple of features:

* cookies
* Multipart-form-data

These are pretty important, so I'll try to get them done in the next few days before releasing.

You can already try via the CLI... to run a http file, you can run something like this:

```
java -jar rawhttp.jar run my.http
```

The help command prints the usage (so far):

```
 java -jar rawhttp.jar help run                                                                
=============== RawHTTP CLI ===============
 https://github.com/renatoathaydes/rawhttp
 rawhttp-cli  version: 1.2.1
 rawhttp-core version: 2.2.1
===========================================

Run sub-command Help.

The 'run' sub-command executes a HTTP file as defined by Jetbrains at

https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

Usage:
  rawhttp run <http-file> [options]

Options:
  * -e --environment <name>
    the name of the environment to use
  * -p --print-response-mode
  *   one of: response|all|body|status|stats
        - response: (default) print the full responses
        - all: print the full response and statistics about each request
        - body: print the response bodies
        - status: print the response status-lines
        - stats: print statistics about each request
  * -l --log-request
      log the request

For more information about the stats response-mode, see the docs for the 'send' sub-command.

Serve sub-command Help.

The 'serve' sub-command is used to serve a local directory via HTTP.

Request paths may match a file name with or without its extension.
If more than one file exists with the same name but different extensions,
the server attempts to use the request Accept header to disambiguate.

Usage:
  rawhttp serve <dir> [options]

Options:
  * -l --log-requests
      log requests received by the server
  * -m --media-types <file>
      use custom Media-Type mappings
  * -p --port <port-number>
      the port to listen on
  * -r --root-path <path>
      the path to use as the root path (not incl. in file path, only URL)

```

**Comment by renatoathaydes** [comment]
I've released a beta version of the RawHTTP CLI which can run Jetbrains's HTTP files.

https://bintray.com/renatoathaydes/maven/rawhttp-req-in-edit

You can get the jars from JCEnter (soon Maven Central as well).

To run a HTTP file, run:

```
java -jar rawhttp-cli.jar run my.http
```

To log requests, use `-l` and to disable TLS validation, use `-i`:

```
java -jar rawhttp-cli.jar run my.http -l -i
```

Variables are supported as described in the JetBrains docs: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#using_request_vars

**Comment by renatoathaydes** [comment]
Oh, and it can print statistics as well...

Here's the updated options:

```
Run sub-command Help.

The 'run' sub-command executes a HTTP file as defined by Jetbrains at

https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

Usage:
  rawhttp run <http-file> [options]

Options:
  * -e --environment <name>
    the name of the environment to use
  * -c --cookiejar <file>
    the file to use as a cookie jar
  * -p --print-response-mode
  *   one of: response|all|body|status|stats
        - response: (default) print the full responses
        - all: print the full response and statistics about each request
        - body: print the response bodies
        - status: print the response status-lines
        - stats: print statistics about each request
  * -l --log-request
      log the request

For more information about the stats response-mode, see the docs for the 'send' sub-command.
```
