### ISSUE TITLE
Failed to parse request with InputStream (absolute-form + host header)

### ISSUE THREAD

**Issue by vladiMishaiev** [renatoathaydes/rawhttp#4]
Hi,
While parsing a request with client.InputStream getting "Host specified both in Host header and in request line" exception. Request is sent with absolute-form path with identical host header.

Note that by RFC2616 in this case host header must be ignored.

I'm testing it with a proxy server, Proxy servers receive requests with absolute-form paths.

**Comment by renatoathaydes** [comment]
Just remove the `Host` header, by default, it will be inserted automatically.
But you're correct, this should be allowed... I will change soon.

**Comment by renatoathaydes** [comment]
Can you post an example of such request?
