### ISSUE TITLE
rawhttp api ?

### ISSUE THREAD

**Issue by Taymindis** [renatoathaydes/rawhttp#41]
I am wondering if you have api for

```
  .setMethod(...)
  .setHost(...)
  .setHeaders(Map ....)


  then.

rawHttp.outputStream become rawHttpResult. Because i want to use it for Nonblocking IO methodology
```

**Comment by renatoathaydes** [comment]
RawHTTP is built on synchronous IO. It will never support async, sorry.
When [Project Loom](https://wiki.openjdk.java.net/display/loom/Main) arrives at the JVM  , you will be able to run on Virtual Threads. I [wrote about it](https://renato.athaydes.com/posts/taking-loom-for-a-spin.html) on my blog.
