### ISSUE TITLE
Can a HTTP request be made over a SocketChannel

### ISSUE THREAD

**Issue by FDelporte** [renatoathaydes/rawhttp#43]
I'm investigating if I can use rawhttp to call devices over a UnixDomainSocketAddress. Problem is that these works with SocketChannel which has read and write, but not getInputStream and getOutputStream.

Would be great if something like this was possible...

```
try (var clientChannel = SocketChannel.open(UnixDomainSocketAddress.of(address))) {
   RawHttp rawHttp = new RawHttp();

   RawHttpRequest request = rawHttp.parseRequest(
                    "GET /hello.txt HTTP/1.1\r\n" +
                    "...");
   request.writeTo(clientChannel);
   
   RawHttpResponse<?> response = rawHttp.parseResponse(clientChannel);
   // Do something with response
}
```

**Comment by renatoathaydes** [comment]
Don't these work?

```java
SocketChannel c = ...;
InputStream stream = Channels.newInputStream(c);
request = http.parseRequest(stream);
OutputStream out = Channels.newOutputStream(c);
request.writeTo(out);
```

**Comment by FDelporte** [comment]
@renatoathaydes you're absolutely right! made it work like this:

```
try (var socketChannel = SocketChannel.open(UnixDomainSocketAddress.of(address))) {
    RawHttpRequest request = new RawHttp().parseRequest("GET " + path + " HTTP/1.1\r\n"
                + "User-Agent: java-service\r\n"
                + "Host: www.something.com\r\n"
                + "Accept-Language: en");

    OutputStream out = Channels.newOutputStream(socketChannel);
    request.writeTo(out);

    RawHttpResponse<?> response = new RawHttp().parseResponse(Channels.newInputStream(socketChannel));
    // Do something with response
}
```

**Comment by FDelporte** [comment]
you are now officially my hero of the day ;-)
this is one nice piece of library you created!!!

**Comment by renatoathaydes** [comment]
Haha, thanks, glad to know it is useful to you.

**Comment by FDelporte** [comment]
@renatoathaydes is there a way to add a timeout to both write and response?

**Comment by renatoathaydes** [comment]
You need access to the `Socket` to do that as the socket itself has a timeout.

If you're using a `TcpRawHttpClient` to make requests, you can use the constructor that takes a `TcpRawHttpClientOptions` instance and use a class that lets you implement `Socket createSocket(boolean useHttps, String host, int port) throws IOException`...

The easiest way is to sub-type `rawhttp.core.client.TcpRawHttpClient.DefaultOptions`:

```java
class MyOptions extends TcpRawHttpClient.DefaultOptions {
    @Override protected Socket createSocket(boolean useHttps, String host, int port) throws IOException {
        var socket = super.createSocket(useHttps, host, port);
        socket.setSoTimeout(someTimeout);
        return socket;
    }
}
```

Similarly, if you're using `TcpRawHttpServer`, implement `TcpRawHttpServerOptions`, pass your implementation to the constructor of `TcpRawHttpServer`, and implement `ServerSocket getServerSocket() throws IOException` something like this:

```java
new TcpRawHttpServer(() -> {
  var socket = new ServerSocket(port);
  socket.setSoTimeout(someTimeout);
  return socket;
});
```

The reader and writer methods will then timeout according to the socket timeouts.

Notice that on the client, there's also a connect timeout (as opposed to socket read timeout) which can be when you explicilty call `connect` on the socket, as explained in the first answer at https://stackoverflow.com/questions/5632279/how-to-set-timeout-on-client-socket-connection ... you might want to do that also.

**Comment by FDelporte** [comment]
thanks for the detailed info! will need to investigate how to combine all this with the SocketChannel I'm using...

`try (var socketChannel = SocketChannel.open(UnixDomainSocketAddress.of(address))) {`
