### ISSUE TITLE
It does not follow redirect to the page when getting redirection

### ISSUE THREAD

**Issue by Taymindis** [renatoathaydes/rawhttp#47]
I got a page response need to follow redirect, but it seemed like not working

```
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://xxxx.heroku.com/.......
```

**Comment by Taymindis** [comment]
it's not working.

```
  RawHttp rawHttp = new RawHttp();
        RawHttpClient rawHttpClient = new RedirectingRawHttpClient(new RawHttpClient<RawHttpResponse<Void>>() {
            @Override
            public RawHttpResponse send(RawHttpRequest rawHttpRequest) throws IOException {
                Socket socket = new Socket("www.github.com", 80);
                rawHttpRequest.writeTo(socket.getOutputStream());
                return rawHttp.parseResponse(socket.getInputStream());
            }
        }, 10);

        RawHttpRequest request = rawHttp.parseRequest(
                "GET /......");

        RawHttpResponse<?> response = rawHttpClient.send(request);

        // call "eagerly()" in order to download the body
        System.out.println(response.eagerly());
```

**Comment by renatoathaydes** [comment]
Why are you implementing `RawHttpClient` yourself, try using `TcpRawHttpClient` instead.
Also, what is not working? Do you still get the 301 with the above code?

See an example of using this client in the RawHTTP CLI: https://github.com/renatoathaydes/rawhttp/blob/master/rawhttp-cli/src/main/java/rawhttp/cli/Main.java#L258

**Comment by renatoathaydes** [comment]
@Taymindis I have created [a sample]https://github.com/renatoathaydes/rawhttp/commit/532a817a60ffa15cb6b8dee598e6f6958fda7144) to help you.

If you want, you can test it on a real server by adding this code as well:

```java
            response = rawClient.send(http.parseRequest("GET http://google.com\nAccept: */*")).eagerly();
            System.out.println(response);

            response = redirectingRawHttpClient.send(http.parseRequest("GET http://google.com\nAccept: */*")).eagerly();
            System.out.println(response);

```

The  first printed response will show that google will respond with a 302 response (as the client used does not follow redirects).

The second one will show that the client follows the redirect and gets the 200 response you would expect.

If you still have trouble, you need to give me the exact request and response that is causing trouble.
