### ISSUE TITLE
Timeout for RawHttp.parseResponse() and RawHttp.parseRequest

### ISSUE THREAD

**Issue by wenkst** [renatoathaydes/rawhttp#5]
Hi,

You made a really great library. There is some small issue that stopps me at the moment from using it. I'm not sure if it is already possible or not but I could not figure out a way to set some sort of a timeout to parseResponse and parseRequest. The problem is that when the server sends a response that is not complete the parseRequest method hangs forever. The same problem occurres for the parseResponse. 

It would be really great if there was a possibility to set a timeout to ensure the method does not block forever. Sometimes it can take a long time until the socket is closed and the method returns.

**Comment by renatoathaydes** [comment]
You  could set a timeout on the socket used by RawHTTP to receive the response.
You just need to provide your own implementation of `TcpRawHttpClientOptions` to the client constructor, or `TcpRawHttpServerOptions` for the server.

Thanks for the compliment to the lib!

**Comment by wenkst** [comment]
Thank you very much! Setting the socket timeout is what I need.
