### ISSUE TITLE
Error: not enough thanks to give.

### ISSUE THREAD

**Issue by mobius3** [renatoathaydes/rawhttp#50]
After successfully performing a GET request with a body(!!!!1) required by the ugliest API I've ever used, thanks to this library, I got this error.

Seriously, this library saved my ass. Thanks. You can close this issue now.

**Comment by renatoathaydes** [comment]
Haha! Yeah, too many libraries hold the user's hands as if we were all children and could not handle lower level stuff :D.

RawHTTP lets you do whatever you want and only does minimal validation of HTTP messages which are required by the core HTTP spec (which says nothing about GET not having bodies!).

Glad it was of use to you :).
