### ISSUE TITLE
RequestLine#parseRequestLine(String statusLine) escapes already-escaped path

### ISSUE THREAD

**Issue by lukewpatterson** [renatoathaydes/rawhttp#6]
e.g.
```
GET /hello?field=encoded%20value HTTP/1.0
```
Creates a URI with a query value of "field=encoded%**25**20value".  The "%" in the "%20" itself gets escaped to "%25".

Example test, with failure results: https://github.com/lukewpatterson/rawhttp/commit/295f1726fce8dcf7754ea9f2d610f9da6736f409

In my debugging it makes it all the way [here](https://github.com/lukewpatterson/rawhttp/blob/295f1726fce8dcf7754ea9f2d610f9da6736f409/rawhttp-core/src/main/java/rawhttp/core/HttpMetadataParser.java#L438) before the URI class double-escapes it.  I hacked some stuff up in another project with a URLDecoder to compensate but it isn't clean enough for a Pull Request.

</br>
</br>

P.S. Great library!  It's pairing up nicely with some [GoReplay](https://github.com/buger/goreplay/wiki/Saving-and-Replaying-from-file#file-format)-based testing I'm doing.  Keep up the good work.

**Comment by renatoathaydes** [comment]
Hi, thanks for the kind words!

One of the main concerns in RawHTTP is performance. For that reason, I don't want to make RawHTTP have to check if the provided HTTP messages are pre-encoded or not: it assumes messages are not.

But it would be cool if we could support re-playing requests recorded with GoReplay and other tools! So, not sure what would the best approach be.

In situations like this, I normally add an option to `RawHttpOptions` to let the users decide.

Would that be ok?

**Comment by lukewpatterson** [comment]
Hi Renato, 

For anyone taking raw http from a 3rd party source and feeding it to this library, like I am, I think it'd be surprising to need to decode the raw http content before sending to rawhttp.  If it needs to be an option, the least surprise would be if rawhttp handled encoded content by default.  To steal from the XOM library's goals - "correctness, simplicity, and performance, in that order" seems like a good philosophy.

In my case, it is especially hard to workaround %20 because if I replace it with a space for rawhttp's sake, it run into this -
https://github.com/renatoathaydes/rawhttp/blob/91fccad19292be8ae6489dd4a9aae62c481aa7d5/rawhttp-core/src/main/java/rawhttp/core/HttpMetadataParser.java#L145

**Comment by lukewpatterson** [comment]
Really either way for options default works for me, in my case I'd always configure it to handle encoding for me so I wouldn't have to worry about it.  👍

**Comment by renatoathaydes** [comment]
> For anyone taking raw http from a 3rd party source and feeding it to this library, like I am, I think it'd be surprising to need to decode the raw http content before sending to rawhttp

I agree! The funny thing is that I wrote RawHTTP to be able to write HTTP by hand! So it would be surprising for me to have to encode the strings in the start-line :)

So, as usual, depends on where you're coming from. But I think it does make sense to make RawHTTP expect encoded contents by default because otherwise it would run into parsing issues (like you seem to have!) as separators would be ambiguous.

So I propose to make the default should be that the request/response must be encoded properly (so it can be sent down the wire as it is, mostly) but with an option to try to encode the message if an error is found.

Should work for everyone.

**Comment by renatoathaydes** [comment]
Please try using version 2.1, this should be fixed now.

**Comment by lukewpatterson** [comment]
Thanks @renatoathaydes it works great!
