### ISSUE TITLE
content-security-policy-report-only header very big.

### ISSUE THREAD

**Issue by fhertz** [renatoathaydes/rawhttp#60]
hello,

Some webstite have a big value on content-security-policy-report-only
we got this Exception : 
InvalidHttpResponse{message='Header value is too long', lineNumber=4}
How can we modify the maxHeaderValueLength on Rawhttp ?

Thanks.

**Comment by renatoathaydes** [comment]
You need to pass in a `RawHttpOptions` object to `RawHttp` which sets the max value.

See https://github.com/renatoathaydes/rawhttp/blob/master/rawhttp-core/src/main/java/rawhttp/core/RawHttpOptions.java#L142
