### ISSUE TITLE
Post request 

### ISSUE THREAD

**Issue by vladiMishaiev** [renatoathaydes/rawhttp#8]
Hi, Having trouble sending a simple rest request parsed from string.
while sending the following 
` try{
                Socket serverSocket = null;
                RawHttp http = new RawHttp();
                RawHttpRequest request = null;

                serverSocket = new Socket("localhost", 8081);

                request = http.parseRequest(
                        "POST /api/events/admin/newEvent HTTP/1.1\r\n" +
                                "Host: localhost\r\n" +
                                "User-Agent: ProxyServer\r\n" +
                                "Accept: application/json\r\n" +
                                "Content-Length: " + 85 + "\r\n" +
                                "\r\n" +
                                "{" +
                                "\"subType\": \"subType\"," +
                                "\"source\": \"proxy\"," +
                                "\"description\": \"Tunnel initiated\"," +
                                "\"ID\": 1000" +
                                "}").eagerly();
                //System.out.println(request.toString() + request.getBody());
                System.out.println("Body: "+request.getBody());
                RawHttpResponse<?> response = null;
                request.eagerly().writeTo(serverSocket.getOutputStream());
                response = http.parseResponse(serverSocket.getInputStream()).eagerly();
                serverSocket.close();
            }`
Getting the following output from sniffer :
`POST /api/events/admin/newEvent HTTP/1.1

Host: localhost
User-Agent: ProxyServer
Accept: application/json
Content-Length: 85

{"subType": "subType","source": "proxy","description": "Tunnel initiated","ID": 1000}`

Seems that an extra CRLF is inserted after the start line and after the headers.
What did I miss ?

Thanks,

**Comment by renatoathaydes** [comment]
I wrote this to test your problem:

```java
    StringWriter w = new StringWriter();
    RawHttpRequest request = new RawHttp().parseRequest(
            "POST /api/events/admin/newEvent HTTP/1.1\r\n" +
                    "Host: localhost\r\n" +
                    "User-Agent: ProxyServer\r\n" +
                    "Accept: application/json\r\n" +
                    "Content-Length: " + 85 + "\r\n" +
                    "\r\n" +
                    "{" +
                    "\"subType\": \"subType\"," +
                    "\"source\": \"proxy\"," +
                    "\"description\": \"Tunnel initiated\"," +
                    "\"ID\": 1000" +
                    "}").eagerly().eagerly();
    request.writeTo(new WriterOutputStream(w));
    System.out.println(w.toString().replace("\r", "\\r").replace("\n", "\\n"));
```

It prints the expected output:

```
POST /api/events/admin/newEvent HTTP/1.1\r\n
Host: localhost\r\n
User-Agent: ProxyServer\r\n
Accept: application/json\r\n
Content-Length: 85\r\n
\r\n
{"subType": "subType","source": "proxy","description": "Tunnel initiated","ID": 1000}
```

I intentionally called `eagerly()` twice because you're doing that in your example, but that doesn't make a difference... so something else is causing your problem. Is this the actual code you're trying to run?

Are you using the latest version of rawhttp?
